// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'git_api.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

GitApi _$GitApiFromJson(Map<String, dynamic> json) => GitApi(
      login: json['login'] as String?,
      id: json['id'] as int?,
      node_id: json['node_id'] as String?,
      avatar_url: json['avatar_url'] as String?,
      gravatar_id: json['gravatar_id'] as String?,
      url: json['url'] as String?,
      html_url: json['html_url'] as String?,
      followers_url: json['followers_url'] as String?,
      following_url: json['following_url'] as String?,
      gists_url: json['gists_url'] as String?,
      starred_url: json['starred_url'] as String?,
      subscriptions_url: json['subscriptions_url'] as String?,
      organizations_url: json['organizations_url'] as String?,
      repos_url: json['repos_url'] as String?,
      events_url: json['events_url'] as String?,
      received_events_url: json['received_events_url'] as String?,
      type: json['type'] as String?,
      site_admin: json['site_admin'] as bool?,
      name: json['name'] as String?,
      company: json['company'],
      blog: json['blog'] as String?,
      location: json['location'] as String?,
      email: json['email'],
      hireable: json['hireable'],
      bio: json['bio'] as String?,
      twitter_username: json['twitter_username'] as String?,
      public_repos: json['public_repos'] as int?,
      public_gists: json['public_gists'] as int?,
      followers: json['followers'] as int?,
      following: json['following'] as int?,
      created_at: json['created_at'] as String?,
      updated_at: json['updated_at'] as String?,
    );

Map<String, dynamic> _$GitApiToJson(GitApi instance) => <String, dynamic>{
      'login': instance.login,
      'id': instance.id,
      'node_id': instance.node_id,
      'avatar_url': instance.avatar_url,
      'gravatar_id': instance.gravatar_id,
      'url': instance.url,
      'html_url': instance.html_url,
      'followers_url': instance.followers_url,
      'following_url': instance.following_url,
      'gists_url': instance.gists_url,
      'starred_url': instance.starred_url,
      'subscriptions_url': instance.subscriptions_url,
      'organizations_url': instance.organizations_url,
      'repos_url': instance.repos_url,
      'events_url': instance.events_url,
      'received_events_url': instance.received_events_url,
      'type': instance.type,
      'site_admin': instance.site_admin,
      'name': instance.name,
      'company': instance.company,
      'blog': instance.blog,
      'location': instance.location,
      'email': instance.email,
      'hireable': instance.hireable,
      'bio': instance.bio,
      'twitter_username': instance.twitter_username,
      'public_repos': instance.public_repos,
      'public_gists': instance.public_gists,
      'followers': instance.followers,
      'following': instance.following,
      'created_at': instance.created_at,
      'updated_at': instance.updated_at,
    };

Followers _$FollowersFromJson(Map<String, dynamic> json) => Followers(
      login: json['login'] as String?,
      id: json['id'] as int?,
      node_id: json['node_id'] as String?,
      avatar_url: json['avatar_url'] as String?,
      gravatar_id: json['gravatar_id'] as String?,
      url: json['url'] as String?,
      html_url: json['html_url'] as String?,
      followers_url: json['followers_url'] as String?,
      following_url: json['following_url'] as String?,
      gists_url: json['gists_url'] as String?,
      starred_url: json['starred_url'] as String?,
      subscriptions_url: json['subscriptions_url'] as String?,
      organizations_url: json['organizations_url'] as String?,
      repos_url: json['repos_url'] as String?,
      events_url: json['events_url'] as String?,
      received_events_url: json['received_events_url'] as String?,
      type: json['type'] as String?,
      site_admin: json['site_admin'] as bool?,
    );

Map<String, dynamic> _$FollowersToJson(Followers instance) => <String, dynamic>{
      'login': instance.login,
      'id': instance.id,
      'node_id': instance.node_id,
      'avatar_url': instance.avatar_url,
      'gravatar_id': instance.gravatar_id,
      'url': instance.url,
      'html_url': instance.html_url,
      'followers_url': instance.followers_url,
      'following_url': instance.following_url,
      'gists_url': instance.gists_url,
      'starred_url': instance.starred_url,
      'subscriptions_url': instance.subscriptions_url,
      'organizations_url': instance.organizations_url,
      'repos_url': instance.repos_url,
      'events_url': instance.events_url,
      'received_events_url': instance.received_events_url,
      'type': instance.type,
      'site_admin': instance.site_admin,
    };

Repo _$RepoFromJson(Map<String, dynamic> json) => Repo(
      id: json['id'] as int?,
      node_id: json['node_id'] as String?,
      name: json['name'] as String?,
      fullName: json['fullName'] as String?,
      private: json['private'] as bool?,
      owner: json['owner'] == null
          ? null
          : Owner.fromJson(json['owner'] as Map<String, dynamic>),
      html_url: json['html_url'] as String?,
      description: json['description'] as String?,
      fork: json['fork'] as bool?,
      url: json['url'] as String?,
      forks_url: json['forks_url'] as String?,
      keys_url: json['keys_url'] as String?,
      collaborators_url: json['collaborators_url'] as String?,
      teams_url: json['teams_url'] as String?,
      hooks_url: json['hooks_url'] as String?,
      issue_events_url: json['issue_events_url'] as String?,
      events_url: json['events_url'] as String?,
      assignees_url: json['assignees_url'] as String?,
      branches_url: json['branches_url'] as String?,
      tags_url: json['tags_url'] as String?,
      blobs_url: json['blobs_url'] as String?,
      gitTags_url: json['gitTags_url'] as String?,
      gitRefs_url: json['gitRefs_url'] as String?,
      trees_url: json['trees_url'] as String?,
      statuses_url: json['statuses_url'] as String?,
      languages_url: json['languages_url'] as String?,
      stargazers_url: json['stargazers_url'] as String?,
      contributors_url: json['contributors_url'] as String?,
      subscribers_url: json['subscribers_url'] as String?,
      subscription_url: json['subscription_url'] as String?,
      commits_url: json['commits_url'] as String?,
      gitCommits_url: json['gitCommits_url'] as String?,
      comments_url: json['comments_url'] as String?,
      issueComment_url: json['issueComment_url'] as String?,
      contents_url: json['contents_url'] as String?,
      compare_url: json['compare_url'] as String?,
      merges_url: json['merges_url'] as String?,
      archive_url: json['archive_url'] as String?,
      downloads_url: json['downloads_url'] as String?,
      issues_url: json['issues_url'] as String?,
      pulls_url: json['pulls_url'] as String?,
      milestones_url: json['milestones_url'] as String?,
      notifications_url: json['notifications_url'] as String?,
      labels_url: json['labels_url'] as String?,
      releases_url: json['releases_url'] as String?,
      deployments_url: json['deployments_url'] as String?,
      created_at: json['created_at'] as String?,
      updated_at: json['updated_at'] as String?,
      pushedAt: json['pushedAt'] as String?,
      git_url: json['git_url'] as String?,
      ssh_url: json['ssh_url'] as String?,
      clone_url: json['clone_url'] as String?,
      svn_url: json['svn_url'] as String?,
      homepage: json['homepage'] as String?,
      size: json['size'] as int?,
      stargazersCount: json['stargazersCount'] as int?,
      watchersCount: json['watchersCount'] as int?,
      language: json['language'],
      hasIssues: json['hasIssues'] as bool?,
      hasProjects: json['hasProjects'] as bool?,
      hasDownloads: json['hasDownloads'] as bool?,
      hasWiki: json['hasWiki'] as bool?,
      hasPages: json['hasPages'] as bool?,
      hasDiscussions: json['hasDiscussions'] as bool?,
      forksCount: json['forksCount'] as int?,
      mirror_url: json['mirror_url'],
      archived: json['archived'] as bool?,
      disabled: json['disabled'] as bool?,
      openIssuesCount: json['openIssuesCount'] as int?,
      license: json['license'] == null
          ? null
          : License.fromJson(json['license'] as Map<String, dynamic>),
      allowForking: json['allowForking'] as bool?,
      isTemplate: json['isTemplate'] as bool?,
      webCommitSignoff: json['webCommitSignoff'] as bool?,
      topics: json['topics'] as List<dynamic>?,
      visibility: json['visibility'] as String?,
      forks: json['forks'] as int?,
      openIssues: json['openIssues'] as int?,
      watchers: json['watchers'] as int?,
      defaultBranch: json['defaultBranch'] as String?,
      permissions: json['permissions'] == null
          ? null
          : Permissions.fromJson(json['permissions'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$RepoToJson(Repo instance) => <String, dynamic>{
      'id': instance.id,
      'node_id': instance.node_id,
      'name': instance.name,
      'fullName': instance.fullName,
      'private': instance.private,
      'owner': instance.owner,
      'html_url': instance.html_url,
      'description': instance.description,
      'fork': instance.fork,
      'url': instance.url,
      'forks_url': instance.forks_url,
      'keys_url': instance.keys_url,
      'collaborators_url': instance.collaborators_url,
      'teams_url': instance.teams_url,
      'hooks_url': instance.hooks_url,
      'issue_events_url': instance.issue_events_url,
      'events_url': instance.events_url,
      'assignees_url': instance.assignees_url,
      'branches_url': instance.branches_url,
      'tags_url': instance.tags_url,
      'blobs_url': instance.blobs_url,
      'gitTags_url': instance.gitTags_url,
      'gitRefs_url': instance.gitRefs_url,
      'trees_url': instance.trees_url,
      'statuses_url': instance.statuses_url,
      'languages_url': instance.languages_url,
      'stargazers_url': instance.stargazers_url,
      'contributors_url': instance.contributors_url,
      'subscribers_url': instance.subscribers_url,
      'subscription_url': instance.subscription_url,
      'commits_url': instance.commits_url,
      'gitCommits_url': instance.gitCommits_url,
      'comments_url': instance.comments_url,
      'issueComment_url': instance.issueComment_url,
      'contents_url': instance.contents_url,
      'compare_url': instance.compare_url,
      'merges_url': instance.merges_url,
      'archive_url': instance.archive_url,
      'downloads_url': instance.downloads_url,
      'issues_url': instance.issues_url,
      'pulls_url': instance.pulls_url,
      'milestones_url': instance.milestones_url,
      'notifications_url': instance.notifications_url,
      'labels_url': instance.labels_url,
      'releases_url': instance.releases_url,
      'deployments_url': instance.deployments_url,
      'created_at': instance.created_at,
      'updated_at': instance.updated_at,
      'pushedAt': instance.pushedAt,
      'git_url': instance.git_url,
      'ssh_url': instance.ssh_url,
      'clone_url': instance.clone_url,
      'svn_url': instance.svn_url,
      'homepage': instance.homepage,
      'size': instance.size,
      'stargazersCount': instance.stargazersCount,
      'watchersCount': instance.watchersCount,
      'language': instance.language,
      'hasIssues': instance.hasIssues,
      'hasProjects': instance.hasProjects,
      'hasDownloads': instance.hasDownloads,
      'hasWiki': instance.hasWiki,
      'hasPages': instance.hasPages,
      'hasDiscussions': instance.hasDiscussions,
      'forksCount': instance.forksCount,
      'mirror_url': instance.mirror_url,
      'archived': instance.archived,
      'disabled': instance.disabled,
      'openIssuesCount': instance.openIssuesCount,
      'license': instance.license,
      'allowForking': instance.allowForking,
      'isTemplate': instance.isTemplate,
      'webCommitSignoff': instance.webCommitSignoff,
      'topics': instance.topics,
      'visibility': instance.visibility,
      'forks': instance.forks,
      'openIssues': instance.openIssues,
      'watchers': instance.watchers,
      'defaultBranch': instance.defaultBranch,
      'permissions': instance.permissions,
    };

Owner _$OwnerFromJson(Map<String, dynamic> json) => Owner(
      login: json['login'] as String?,
      id: json['id'] as int?,
      node_id: json['node_id'] as String?,
      avatar_url: json['avatar_url'] as String?,
      gravatar_id: json['gravatar_id'] as String?,
      url: json['url'] as String?,
      html_url: json['html_url'] as String?,
      followers_url: json['followers_url'] as String?,
      following_url: json['following_url'] as String?,
      gists_url: json['gists_url'] as String?,
      starred_url: json['starred_url'] as String?,
      subscriptions_url: json['subscriptions_url'] as String?,
      organizations_url: json['organizations_url'] as String?,
      repos_url: json['repos_url'] as String?,
      events_url: json['events_url'] as String?,
      received_events_url: json['received_events_url'] as String?,
      type: json['type'] as String?,
      site_admin: json['site_admin'] as bool?,
    );

Map<String, dynamic> _$OwnerToJson(Owner instance) => <String, dynamic>{
      'login': instance.login,
      'id': instance.id,
      'node_id': instance.node_id,
      'avatar_url': instance.avatar_url,
      'gravatar_id': instance.gravatar_id,
      'url': instance.url,
      'html_url': instance.html_url,
      'followers_url': instance.followers_url,
      'following_url': instance.following_url,
      'gists_url': instance.gists_url,
      'starred_url': instance.starred_url,
      'subscriptions_url': instance.subscriptions_url,
      'organizations_url': instance.organizations_url,
      'repos_url': instance.repos_url,
      'events_url': instance.events_url,
      'received_events_url': instance.received_events_url,
      'type': instance.type,
      'site_admin': instance.site_admin,
    };

License _$LicenseFromJson(Map<String, dynamic> json) => License(
      key: json['key'] as String?,
      name: json['name'] as String?,
      spdx_id: json['spdx_id'] as String?,
      url: json['url'] as String?,
      node_id: json['node_id'] as String?,
    );

Map<String, dynamic> _$LicenseToJson(License instance) => <String, dynamic>{
      'key': instance.key,
      'name': instance.name,
      'spdx_id': instance.spdx_id,
      'url': instance.url,
      'node_id': instance.node_id,
    };

Permissions _$PermissionsFromJson(Map<String, dynamic> json) => Permissions(
      admin: json['admin'] as bool?,
      maintain: json['maintain'] as bool?,
      push: json['push'] as bool?,
      triage: json['triage'] as bool?,
      pull: json['pull'] as bool?,
    );

Map<String, dynamic> _$PermissionsToJson(Permissions instance) =>
    <String, dynamic>{
      'admin': instance.admin,
      'maintain': instance.maintain,
      'push': instance.push,
      'triage': instance.triage,
      'pull': instance.pull,
    };
